In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns=['A', 'B', 'C'], index=['x', 'y', 'z'])

In [4]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [5]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [6]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [7]:
results = pd.read_parquet('./data/results.parquet')
bios = pd.read_csv('./data/bios.csv')

In [8]:
bios.sample(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
63189,63659,Pedro Silveira,1973-12-11,NaN,NaN,NaN,Mexico,NaN,NaN,NaN
28665,28878,Alie van den Bos,1902-01-18,Amsterdam,Noord-Holland,NED,Netherlands,NaN,NaN,2003-07-16
13555,13637,Jan Blomme,1959-05-27,Varsenare,West-Vlaanderen,BEL,Belgium,180.0,73.0,NaN
120053,121907,Roseli Feitosa,1989-03-15,São Paulo,São Paulo,BRA,Brazil,173.0,79.0,NaN
19246,19382,Ichiro Sado,1941-02-05,NaN,NaN,NaN,Japan,171.0,66.0,NaN
112661,113941,Austin Smith,1985-05-20,Cape Town,Western Cape,RSA,South Africa,179.0,73.0,NaN
15146,15248,Dzintars Lācis,1940-05-18,Jelgava,Jelgava,LAT,Soviet Union,180.0,79.0,1992-11-17
133186,136117,Yassine Trabelsi,1990-07-12,Tunis,Tunis,TUN,Tunisia,185.0,63.0,NaN
4618,4634,Dashnyamyn Olzvoi,1949-04-20,NaN,NaN,NaN,Mongolia,176.0,71.0,NaN
66939,67450,Solomone Bole,1974-06-23,Suva,Rewa,FIJ,Fiji,177.0,79.0,NaN

In [9]:
bios.query('born_country=="URU" and born_city=="Tacuarembó"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
8528,8575,Basilio Álvez,1915-07-11,Tacuarembó,Tacuarembó,URU,Uruguay,NaN,NaN,NaN

In [10]:
results[results['athlete_id']==8575]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
13089,1948.0,Summer,Boxing,"Featherweight, Men (Olympic)",Basilio Álvez,8575,URU,None,9.0,True,None

In [11]:
results.query('noc=="URU" and discipline!="Football (Football)"').sort_values('place').dropna(subset=['place', 'medal'])

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
86076,1948.0,Summer,Rowing,"Single Sculls, Men (Olympic)",Eduardo Risso,40426,URU,None,2.0,False,Silver
31451,2000.0,Summer,Cycling Track (Cycling),"Points Race, Men (Olympic)",Milton Wynants,17222,URU,None,2.0,False,Silver
86079,1952.0,Summer,Rowing,"Double Sculls, Men (Olympic)",Juan Antonio Rodríguez,40427,URU,Miguel Seijas,3.0,False,Bronze
86081,1952.0,Summer,Rowing,"Double Sculls, Men (Olympic)",Miguel Seijas,40429,URU,Juan Antonio Rodríguez,3.0,False,Bronze
13116,1964.0,Summer,Boxing,"Bantamweight, Men (Olympic)",Washington Rodríguez,8602,URU,None,3.0,True,Bronze
11268,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Milton Scarón,7065,URU,Uruguay,3.0,False,Bronze
11183,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Carlos Roselló,6996,URU,Uruguay,3.0,False,Bronze
10964,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Wilfredo Peláez,6834,URU,Uruguay,3.0,False,Bronze
10877,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Ariel Olascoaga,6769,URU,Uruguay,3.0,False,Bronze
86064,1932.0,Summer,Rowing,"Single Sculls, Men (Olympic)",Guillermo Douglas,40416,URU,None,3.0,False,Bronze
10767,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Óscar Moglia,6681,URU,Uruguay,3.0,False,Bronze
86067,1948.0,Summer,Rowing,"Double Sculls, Men (Olympic)",William Jones,40419,URU,Juan Antonio Rodríguez,3.0,False,Bronze
86078,1948.0,Summer,Rowing,"Double Sculls, Men (Olympic)",Juan Antonio Rodríguez,40427,URU,William Jones,3.0,False,Bronze
10741,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Raúl Mera,6661,URU,Uruguay,3.0,False,Bronze
9737,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Victorio Cieslinskas,5890,URU,Uruguay,3.0,False,Bronze
10592,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Roberto Lovera,6549,URU,Uruguay,3.0,False,Bronze
9770,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Ramiro Cortés,5914,URU,Uruguay,3.0,False,Bronze
9776,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Héctor Costa,5917,URU,Uruguay,3.0,False,Bronze
10092,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Héctor García,6156,URU,Uruguay,3.0,False,Bronze
10093,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Héctor García,6156,URU,Uruguay,3.0,False,Bronze
9704,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Nelson Chelle,5861,URU,Uruguay,3.0,False,Bronze
9777,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Héctor Costa,5917,URU,Uruguay,3.0,False,Bronze
10151,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Carlos González,6199,URU,Uruguay,3.0,False,Bronze
9542,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Carlos Blixen,5746,URU,Uruguay,3.0,False,Bronze
10568,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Adesio Lombardo,6535,URU,Uruguay,3.0,False,Bronze
9440,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Enrique Baliño,5667,URU,Uruguay,3.0,False,Bronze
9325,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Martín Acosta y Lara,5577,URU,Uruguay,3.0,False,Bronze
9884,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Nelson Demarco,5989,URU,Uruguay,3.0,False,Bronze
10702,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Sergio Matto,6632,URU,Uruguay,3.0,False,Bronze
10701,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Sergio Matto,6632,URU,Uruguay,3.0,False,Bronze
10500,1952.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Tabaré Larre Borges,6486,URU,Uruguay,3.0,False,Bronze
9885,1956.0,Summer,Basketball (Basketball),"Basketball, Men (Olympic)",Nelson Demarco,5989,URU,Uruguay,3.0,False,Bronze

In [12]:
results[results['athlete_id']==17222].sort_values('year')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
31450,1996.0,Summer,Cycling Track (Cycling),"Points Race, Men (Olympic)",Milton Wynants,17222,URU,None,7.0,False,None
31451,2000.0,Summer,Cycling Track (Cycling),"Points Race, Men (Olympic)",Milton Wynants,17222,URU,None,2.0,False,Silver
31452,2004.0,Summer,Cycling Track (Cycling),"Points Race, Men (Olympic)",Milton Wynants,17222,URU,None,9.0,False,None
31453,2004.0,Summer,Cycling Track (Cycling),"Madison, Men (Olympic)",Milton Wynants,17222,URU,Tomás Margalef,10.0,False,None
31454,2008.0,Summer,Cycling Track (Cycling),"Points Race, Men (Olympic)",Milton Wynants,17222,URU,None,16.0,False,None

In [13]:
olympics = pd.merge(results, bios, how='left', on='athlete_id')

In [14]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

In [15]:
results.query('noc=="URU" and type=="Winter"')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
214035,1998.0,Winter,Alpine Skiing (Skiing),"Slalom, Men (Olympic)",Gabriel Hottegindre,99520,URU,None,24.0,False,None

In [16]:
results['noc'].sort_values().unique()

array(['AFG', 'AHO', 'ALB', 'ALG', 'AND', 'ANG', 'ANT', 'ANZ', 'ARG',
       'ARM', 'ARU', 'ASA', 'AUS', 'AUT', 'AZE', 'BAH', 'BAN', 'BAR',
       'BDI', 'BEL', 'BEN', 'BER', 'BHU', 'BIH', 'BIZ', 'BLR', 'BOH',
       'BOL', 'BOT', 'BRA', 'BRN', 'BRU', 'BUL', 'BUR', 'CAF', 'CAM',
       'CAN', 'CAY', 'CGO', 'CHA', 'CHI', 'CHN', 'CIV', 'CMR', 'COD',
       'COK', 'COL', 'COM', 'COR', 'CPV', 'CRC', 'CRO', 'CRT', 'CUB',
       'CYP', 'CZE', 'DEN', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'EOR',
       'ERI', 'ESA', 'ESP', 'EST', 'ETH', 'EUN', 'FIJ', 'FIN', 'FRA',
       'FRG', 'FSM', 'GAB', 'GAM', 'GBR', 'GBS', 'GDR', 'GEO', 'GEQ',
       'GER', 'GHA', 'GRE', 'GRN', 'GUA', 'GUI', 'GUM', 'GUY', 'HAI',
       'HKG', 'HON', 'HUN', 'INA', 'IND', 'IOA', 'IRI', 'IRL', 'IRQ',
       'ISL', 'ISR', 'ISV', 'ITA', 'IVB', 'JAM', 'JOR', 'JPN', 'KAZ',
       'KEN', 'KGZ', 'KIR', 'KOR', 'KOS', 'KSA', 'KUW', 'LAO', 'LAT',
       'LBA', 'LBN', 'LBR', 'LCA', 'LES', 'LIE', 'LTU', 'LUX', 'MAD',
       'MAL', 'MAR', 'MAS', 'MAW', 'MDA', 'MDV', 'MEX', 'MGL', 'MHL',
       'MKD', 'MLI', 'MLT', 'MNE', 'MON', 'MOZ', 'MRI', 'MTN', 'MYA',
       'NAM', 'NBO', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'NOR', 'NRU',
       'NZL', 'OMA', 'PAK', 'PAN', 'PAR', 'PER', 'PHI', 'PLE', 'PLW',
       'PNG', 'POL', 'POR', 'PRK', 'PUR', 'QAT', 'RHO', 'ROC', 'ROU',
       'RSA', 'RUS', 'RWA', 'SAA', 'SAM', 'SCG', 'SEN', 'SEY', 'SGP',
       'SKN', 'SLE', 'SLO', 'SMR', 'SOL', 'SOM', 'SRB', 'SRI', 'SSD',
       'STP', 'SUD', 'SUI', 'SUR', 'SVK', 'SWE', 'SWZ', 'SYR', 'TAN',
       'TCH', 'TGA', 'THA', 'TJK', 'TKM', 'TLS', 'TOG', 'TPE', 'TTO',
       'TUN', 'TUR', 'TUV', 'UAE', 'UAR', 'UGA', 'UKR', 'URS', 'URU',
       'USA', 'UZB', 'VAN', 'VEN', 'VIE', 'VIN', 'VNM', 'WIF', 'YAR',
       'YEM', 'YMD', 'YUG', 'ZAM', 'ZIM', None], dtype=object)

In [17]:
olympics.query('type=="Winter" and medal=="Bronze" and born_country=="POL" and year==1972')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
209273,1972.0,Winter,Biathlon,"4 × 7.5 kilometres Relay, Men (Olympic)",Dieter Speer,97720,GDR,East Germany,3.0,False,Bronze,Dieter Speer,1942-02-24,Legnica,Dolnośląskie,POL,East Germany,176.0,68.0,NaN

In [18]:
olympics[olympics['noc'] == 'URU'].dropna(subset=['medal']).groupby(['born_region'])['medal'].value_counts().unstack(fill_value=0)[['Gold', 'Silver', 'Bronze']].sort_values(['Gold', 'Silver', 'Bronze'], ascending=False)

medal           Gold  Silver  Bronze
born_region
Montevideo        27       1      19
Salto              2       0       1
Paysandú           0       1       3
Canelones          0       0       2
Soriano            0       0       2
San José           0       0       1
Treinta y Tres     0       0       1

In [19]:
results[(results['noc']=='URU') & (results['year']==1924)].sort_values('place')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
50492,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Alfredo Zibechi,27672,URU,Uruguay,1.0,False,Gold
50489,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Santos Urdinarán,27670,URU,Uruguay,1.0,False,Gold
50488,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Humberto Tomassina,27668,URU,Uruguay,1.0,False,Gold
50486,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Héctor Scarone,27667,URU,Uruguay,1.0,False,Gold
50485,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Ángel Romano,27666,URU,Uruguay,1.0,False,Gold
50482,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Pedro Petrone,27664,URU,Uruguay,1.0,False,Gold
50481,1924.0,Summer,Football (Football),"Football, Men (Olympic)",José Naya,27663,URU,Uruguay,1.0,False,Gold
50479,1924.0,Summer,Football (Football),"Football, Men (Olympic)",José Nasazzi,27662,URU,Uruguay,1.0,False,Gold
50477,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Andrés Mazali,27661,URU,Uruguay,1.0,False,Gold
50476,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Alfredo Ghierra,27660,URU,Uruguay,1.0,False,Gold
50471,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Pedro Cea,27656,URU,Uruguay,1.0,False,Gold
50464,1924.0,Summer,Football (Football),"Football, Men (Olympic)",Pedro Arispe,27650,URU,Uruguay,1.0,False,Gold
50462,1924.0,Summer,Football (Football),"Football, Men (Olympic)",José Leandro Andrade,27649,URU,Uruguay,1.0,False,Gold
50491,1924.0,Summer,Football (Football),"Football, Men (Olympic)",José Vidal,27671,URU,Uruguay,1.0,False,Gold
45644,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Conrado Rolando,23640,URU,Uruguay,3.0,False,None
45625,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Domingo Mendy,23634,URU,Uruguay,3.0,False,None
45631,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Pedro Mendy,23635,URU,Uruguay,3.0,False,None
45605,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Héctor Belo,23626,URU,Uruguay,3.0,False,None
45612,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Santos Ferreira,23629,URU,Uruguay,3.0,False,None
45611,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Santos Ferreira,23629,URU,Uruguay,4.0,False,None
45603,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Héctor Belo,23626,URU,Uruguay,4.0,False,None
45623,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Domingo Mendy,23634,URU,Uruguay,4.0,False,None
45642,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Conrado Rolando,23640,URU,Uruguay,4.0,False,None
45604,1924.0,Summer,Fencing,"Sabre, Individual, Men (Olympic)",Héctor Belo,23626,URU,None,5.0,False,None
45620,1924.0,Summer,Fencing,"Foil, Individual, Men (Olympic)",Domingo Mendy,23634,URU,None,5.0,False,None
45627,1924.0,Summer,Fencing,"Foil, Individual, Men (Olympic)",Pedro Mendy,23635,URU,None,5.0,False,None
45648,1924.0,Summer,Fencing,"Foil, Individual, Men (Olympic)",Gilberto Tellechea,23643,URU,None,5.0,False,None
45622,1924.0,Summer,Fencing,"Épée, Individual, Men (Olympic)",Domingo Mendy,23634,URU,None,7.0,False,None
45602,1924.0,Summer,Fencing,"Épée, Individual, Men (Olympic)",Héctor Belo,23626,URU,None,7.0,False,None
45624,1924.0,Summer,Fencing,"Sabre, Individual, Men (Olympic)",Domingo Mendy,23634,URU,None,8.0,False,None
45643,1924.0,Summer,Fencing,"Sabre, Individual, Men (Olympic)",Conrado Rolando,23640,URU,None,8.0,False,None
45641,1924.0,Summer,Fencing,"Épée, Individual, Men (Olympic)",Conrado Rolando,23640,URU,None,8.0,False,None
45610,1924.0,Summer,Fencing,"Épée, Individual, Men (Olympic)",Santos Ferreira,23629,URU,None,9.0,False,None
45630,1924.0,Summer,Fencing,"Sabre, Individual, Men (Olympic)",Pedro Mendy,23635,URU,None,9.0,False,None
13110,1924.0,Summer,Boxing,"Lightweight, Men (Olympic)",Julio César Nicolari,8596,URU,None,9.0,True,None
13098,1924.0,Summer,Boxing,"Featherweight, Men (Olympic)",Manuel Esmoris,8584,URU,None,9.0,True,None
13114,1924.0,Summer,Boxing,"Flyweight, Men (Olympic)",Andrés Recalde,8600,URU,None,17.0,True,None
13102,1924.0,Summer,Boxing,"Bantamweight, Men (Olympic)",Mario González,8588,URU,None,17.0,True,None
13096,1924.0,Summer,Boxing,"Lightweight, Men (Olympic)",Liberto Corney,8582,URU,None,17.0,True,None
45601,1924.0,Summer,Fencing,"Foil, Team, Men (Olympic)",Héctor Belo,23626,URU,Uruguay,NaN,False,None
45621,1924.0,Summer,Fencing,"Foil, Team, Men (Olympic)",Domingo Mendy,23634,URU,Uruguay,NaN,False,None
45628,1924.0,Summer,Fencing,"Foil, Team, Men (Olympic)",Pedro Mendy,23635,URU,Uruguay,NaN,False,None
45629,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Pedro Mendy,23635,URU,Uruguay,NaN,False,None
45640,1924.0,Summer,Fencing,"Foil, Team, Men (Olympic)",Conrado Rolando,23640,URU,Uruguay,NaN,False,None
45649,1924.0,Summer,Fencing,"Foil, Team, Men (Olympic)",Gilberto Tellechea,23643,URU,Uruguay,NaN,False,None
45650,1924.0,Summer,Fencing,"Épée, Team, Men (Olympic)",Gilberto Tellechea,23643,URU,Uruguay,NaN,False,None
45651,1924.0,Summer,Fencing,"Sabre, Team, Men (Olympic)",Gilberto Tellechea,23643,URU,Uruguay,NaN,False,None

In [32]:
olympics.query('year>=1980 and event.str.contains(", Men") and medal=="Gold"').groupby('discipline')[['height_cm', 'weight_kg']].min().sort_values('height_cm', ascending=False).dropna().tail(20)

                                     height_cm  weight_kg
discipline
Ski Jumping (Skiing)                     165.0       51.0
Badminton                                165.0       62.0
Cycling Mountain Bike (Cycling)          164.0       50.0
Table Tennis                             164.0       55.0
Shooting                                 164.0       59.0
Freestyle Skiing (Skiing)                163.0       50.0
Short Track Speed Skating (Skating)      163.0       60.0
Speed Skating (Skating)                  162.0       64.0
Snowboarding (Skiing)                    160.0       50.0
Football (Football)                      160.0       49.0
Figure Skating (Skating)                 160.0       50.0
Hockey                                   159.0       54.0
Athletics                                158.0       45.0
Judo                                     157.0       60.0
Diving (Aquatics)                        155.0       42.0
Artistic Gymnastics (Gymnastics)         155.0       48.0
Wrestling                                153.0       48.0
Boxing                                   150.0       48.0
Weightlifting                            150.0       52.0
Rowing                                   146.0       45.0